### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by davjfish** [leeyuhc/DFO_dyna#1]
Hi, I am trying to deploy your code on a shiny server (ubuntu 18.04), but I am running into some problems when trying to upload a csv:

![image](https://user-images.githubusercontent.com/34521117/78574268-25ef6300-7800-11ea-884a-866d7e46992e.png)

When I check out the logs on the server side, it seems to be a file system error relating to the permissions of the web-user. 

I am wondering if you have successfully deployed your app to a server already and if so, give me some pointers about setting permissions etc. 

I cannot seem to figure out where the [fileInput()](https://shiny.rstudio.com/reference/shiny/latest/fileInput.html) is storing the temp file and if there is a way to specify an alternate location. 

Thanks in advance!

**Comment by leahcrowe** [comment]
Permissions issue on server resolved.
